version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    depends_on:
      - scraper  # This ensures the web service waits for scraper initialization but won't fail if the scraper exits.

  scraper:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./scraper:/app
    command: "npm start"
    restart: always  # Ensures scraper restarts even if it fails
